### ISSUE TITLE
GoHeishaMon crashes when writing to /dev/ttyUSB0

### ISSUE THREAD

**Issue by burt2902** [lsochanowski/GoHeishaMon#26]
GoHeishaMon 1.0.166 successfully installed on CZ_TAW1 with the following changes to the default config:
```
MqttServer="192.168.1.2"
MqttPort="1883"
MqttLogin="aquarea"
MqttPass="REMOVED"
```
Mosquitto server running on 192.168.1.2 receives all messages from other clients but receives only one connection attempt from GoHeishaMon-Pub client and no messages. The only connection attempt happens soon after each CZ_TAW1 reboot.

LuCi is accessible. System log indicates a crash...

```
Mon Nov 28 00:51:54 2022 user.emerg syslog: panic: runtime error: invalid memory address or nil pointer dereference
Mon Nov 28 00:51:54 2022 user.emerg syslog: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x303c3c]
Mon Nov 28 00:51:54 2022 user.emerg syslog: 
Mon Nov 28 00:51:54 2022 user.emerg syslog: goroutine 1 [running]:
Mon Nov 28 00:51:54 2022 user.emerg syslog: go.bug.st/serial.(*unixPort).Write(0x0, 0x5d4a40, 0x6e, 0x6e, 0x1223ac00, 0x8b, 0xb2c97000)
Mon Nov 28 00:51:54 2022 user.emerg syslog: 	/go/src/go.bug.st/serial/serial_unix.go:88 +0x30
Mon Nov 28 00:51:54 2022 user.emerg syslog: main.send_command(0x5d4a40, 0x6e, 0x6e, 0x6e, 0x1)
Mon Nov 28 00:51:54 2022 user.emerg syslog: 	/go/src/github.com/lsochanowski/GoHeishaMon/taw2mqtt.go:1060 +0x94
Mon Nov 28 00:51:54 2022 user.emerg syslog: main.main()
Mon Nov 28 00:51:54 2022 user.emerg syslog: 	/go/src/github.com/lsochanowski/GoHeishaMon/taw2mqtt.go:572 +0xa80
```

Furthermore, the same system log does not indicate creation of /dev/ttyUSB0 device.
The crash doesn't occur if GoHeishaMonConfig.new Device is set to "/dev/ttyS0" which exists.

CZ_TAW1 hardware update requiring a different USB serial kernel driver?

**Comment by burt2902** [comment]
Looks like LuCi system log indicates a crash...

```
Mon Nov 28 00:51:54 2022 user.emerg syslog: panic: runtime error: invalid memory address or nil pointer dereference
Mon Nov 28 00:51:54 2022 user.emerg syslog: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x303c3c]
Mon Nov 28 00:51:54 2022 user.emerg syslog: 
Mon Nov 28 00:51:54 2022 user.emerg syslog: goroutine 1 [running]:
Mon Nov 28 00:51:54 2022 user.emerg syslog: go.bug.st/serial.(*unixPort).Write(0x0, 0x5d4a40, 0x6e, 0x6e, 0x1223ac00, 0x8b, 0xb2c97000)
Mon Nov 28 00:51:54 2022 user.emerg syslog: 	/go/src/go.bug.st/serial/serial_unix.go:88 +0x30
Mon Nov 28 00:51:54 2022 user.emerg syslog: main.send_command(0x5d4a40, 0x6e, 0x6e, 0x6e, 0x1)
Mon Nov 28 00:51:54 2022 user.emerg syslog: 	/go/src/github.com/lsochanowski/GoHeishaMon/taw2mqtt.go:1060 +0x94
Mon Nov 28 00:51:54 2022 user.emerg syslog: main.main()
Mon Nov 28 00:51:54 2022 user.emerg syslog: 	/go/src/github.com/lsochanowski/GoHeishaMon/taw2mqtt.go:572 +0xa80

```

**Comment by burt2902** [comment]
GoHeishaMonConfig.new used:Readonly=true
```
Device="/dev/ttyUSB0"
Loghex=true
ReadInterval=1
Aquarea2mqttCompatible=false
Aquarea2mqttPumpID=""
Mqtt_topic_base="panasonic_heat_pump/main"
Mqtt_set_base="panasonic_heat_pump/commands"
ForceRefreshTime=300
MqttServer="192.168.1.2"
MqttPort="1883"
MqttLogin="aquarea"
MqttPass="hasl0Aquar3A"
SleepAfterCommand=1
MqttClientID="GoHeishaMon-pub"
MqttKeepalive=60
EnableCommand=true
HAAutoDiscover=true
```

**Comment by burt2902** [comment]
Entire GoHeishaMonConfig.new used:
```
Readonly=true
Device="/dev/ttyUSB0"
Loghex=true
ReadInterval=1
Aquarea2mqttCompatible=false
Aquarea2mqttPumpID=""
Mqtt_topic_base="panasonic_heat_pump/main"
Mqtt_set_base="panasonic_heat_pump/commands"
ForceRefreshTime=300
MqttServer="192.168.1.2"
MqttPort="1883"
MqttLogin="aquarea"
MqttPass="REMOVED"
SleepAfterCommand=1
MqttClientID="GoHeishaMon-pub"
MqttKeepalive=60
EnableCommand=true
HAAutoDiscover=true
```

**Comment by burt2902** [comment]
LuCi kernel log

```
[    0.000000] Linux version 3.14.0 (root@A2W-LINUX) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.01 r40838) ) #1 Tue Mar 10 07:21:14 UTC 2020
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019374 (MIPS 24Kc)
[    0.000000] SoC: Qualcomm Atheros QCA9533 rev 2
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x03ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x03ffffff]
[    0.000000] On node 0 totalpages: 16384
[    0.000000] free_area_init_node: node 0, pgdat 803a2420, node_mem_map 81000000
[    0.000000]   Normal zone: 128 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 16384 pages, LIFO batch:3
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line:  board=CUS531 console=ttyS0,115200 mtdparts=spi0.0:256k(u-boot)ro,64k(u-boot-env),6464k(rootfs),6464k(rootfs2),64k(apl),64k(config),1472k(kernel1),1472k(kernel2),64k(art) rootfstype=squashfs,jffs2 noinitrd mem=64M rootfstype=squashfs,jffs2 noinitrd
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 60692K/65536K available (2725K kernel code, 127K rwdata, 580K rodata, 208K init, 185K bss, 4844K reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:51
[    0.000000] Clocks: CPU:650.000MHz, DDR:597.387MHz, AHB:216.666MHz, Ref:25.000MHz
[    0.000000] Calibrating delay loop... 432.53 BogoMIPS (lpj=2162688)
[    0.060000] pid_max: default: 32768 minimum: 301
[    0.060000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.070000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.070000] NET: Registered protocol family 16
[    0.080000] MIPS: machine is Qualcomm Atheros CUS531 reference board
[    0.090000] ar71xx: invalid MDIO id 1
[    0.090000] ar71xx: using random MAC address for eth0
[    0.500000] bio: create slab <bio-0> at 0
[    0.510000] Switched to clocksource MIPS
[    0.520000] NET: Registered protocol family 2
[    0.520000] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.520000] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.530000] TCP: Hash tables configured (established 1024 bind 1024)
[    0.540000] TCP: reno registered
[    0.540000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.540000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.550000] NET: Registered protocol family 1
[    0.550000] PCI: CLS 0 bytes, default 32
[    0.560000] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.580000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.580000] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.590000] msgmni has been set to 118
[    0.600000] io scheduler noop registered
[    0.600000] io scheduler deadline registered (default)
[    0.610000] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.630000] serial8250.0: ttyS0 at MMIO 0x18020000 (irq = 11, base_baud = 1562500) is a 16550A
[    0.640000] console [ttyS0] enabled
[    0.650000] bootconsole [early0] disabled
[    0.660000] m25p80 spi0.0: found gd25q128, expected m25p80
[    0.670000] m25p80 spi0.0: gd25q128 (16384 Kbytes)
[    0.670000] 9 cmdlinepart partitions found on MTD device spi0.0
[    0.680000] Creating 9 MTD partitions on "spi0.0":
[    0.680000] 0x000000000000-0x000000040000 : "u-boot"
[    0.690000] 0x000000040000-0x000000050000 : "u-boot-env"
[    0.700000] 0x000000050000-0x0000006a0000 : "rootfs"
[    0.700000] mtd: device 2 (rootfs) set to be root filesystem
[    0.710000] 1 squashfs-split partitions found on MTD device rootfs
[    0.710000] 0x000000610000-0x0000006a0000 : "rootfs_data"
[    0.720000] 0x0000006a0000-0x000000cf0000 : "rootfs2"
[    0.730000] 0x000000cf0000-0x000000d00000 : "apl"
[    0.740000] 0x000000d00000-0x000000d10000 : "config"
[    0.740000] 0x000000d10000-0x000000e80000 : "kernel1"
[    0.750000] 0x000000e80000-0x000000ff0000 : "kernel2"
[    0.760000] 0x000000ff0000-0x000001000000 : "art"
[    0.780000] libphy: ag71xx_mdio: probed
[    1.420000] ag71xx ag71xx.0: connected to PHY at ag71xx-mdio.1:04 [uid=004dd042, driver=Generic PHY]
[    1.430000] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode:MII
[    1.990000] ag71xx-mdio.1: Found an AR934X built-in switch
[    3.020000] eth1: Atheros AG71xx at 0xba000000, irq 5, mode:GMII
[    3.020000] TCP: cubic registered
[    3.030000] NET: Registered protocol family 17
[    3.030000] 8021q: 802.1Q VLAN Support v1.8
[    3.040000] VFS: Mounted root (squashfs filesystem) readonly on device 31:2.
[    3.050000] Freeing unused kernel memory: 208K (803bc000 - 803f0000)
[    4.600000] random: mktemp urandom read with 34 bits of entropy available
[    5.580000] usbcore: registered new interface driver usbfs
[    5.580000] usbcore: registered new interface driver hub
[    5.590000] usbcore: registered new device driver usb
[    5.600000] Button Hotplug driver version 0.4.1
[    5.620000] SCSI subsystem initialized
[    5.620000] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    5.630000] ehci-platform: EHCI generic platform driver
[    5.640000] ehci-platform ehci-platform: EHCI Host Controller
[    5.640000] ehci-platform ehci-platform: new USB bus registered, assigned bus number 1
[    5.650000] ehci-platform ehci-platform: irq 3, io mem 0x1b000000
[    5.680000] ehci-platform ehci-platform: USB 2.0 started, EHCI 1.00
[    5.690000] hub 1-0:1.0: USB hub found
[    5.690000] hub 1-0:1.0: 1 port detected
[    5.700000] usbcore: registered new interface driver usb-storage
[    6.010000] usb 1-1: new high-speed USB device number 2 using ehci-platform
[    6.160000] hub 1-1:1.0: USB hub found
[    6.160000] hub 1-1:1.0: 4 ports detected
[    6.450000] usb 1-1.2: new full-speed USB device number 3 using ehci-platform
[    7.810000] jffs2: notice: (341) jffs2_build_xattr_subsystem: complete building xattr subsystem, 1 of xdatum (0 unchecked, 0 orphan) and 21 of xref (0 dead, 3 orphan) found.
[    9.690000] NET: Registered protocol family 10
[    9.710000] nf_conntrack version 0.5.0 (951 buckets, 3804 max)
[    9.720000] ip6_tables: (C) 2000-2006 Netfilter Core Team
[    9.740000] Loading modules backported from Linux version v3.2-rc1-229534-gb3e71d7
[    9.750000] Backport generated by backports.git backports-20150129-0-gdd4a670
[    9.760000] ip_tables: (C) 2000-2006 Netfilter Core Team
[    9.790000] nf_conntrack_rtsp v0.6.21 loading
[    9.810000] nf_nat_rtsp v0.6.21 loading
[    9.830000] usbcore: registered new interface driver usbserial
[    9.840000] usbcore: registered new interface driver usbserial_generic
[    9.840000] usbserial: USB Serial support registered for generic
[    9.870000] xt_time: kernel timezone is -0000
[    9.910000] cfg80211: Calling CRDA to update world regulatory domain
[    9.910000] cfg80211: World regulatory domain updated:
[    9.920000] cfg80211:  DFS Master region: unset
[    9.920000] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[    9.930000] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[    9.940000] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[    9.950000] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
[    9.960000] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[    9.970000] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[    9.980000] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
[    9.990000] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
[    9.990000] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
[   10.000000] usbcore: registered new interface driver cp210x
[   10.010000] usbserial: USB Serial support registered for cp210x
[   10.030000] usbcore: registered new interface driver ftdi_sio
[   10.030000] usbserial: USB Serial support registered for FTDI USB Serial Device
[   10.160000] usbcore: registered new interface driver pl2303
[   10.160000] usbserial: USB Serial support registered for pl2303
[   10.170000] PPP generic driver version 2.4.2
[   10.180000] NET: Registered protocol family 24
[   10.310000] ath: EEPROM regdomain: 0x8114
[   10.310000] ath: EEPROM indicates we should expect a country code
[   10.310000] ath: doing EEPROM country->regdmn map search
[   10.310000] ath: country maps to regdmn code: 0x37
[   10.310000] ath: Country alpha2 being used: DE
[   10.310000] ath: Regpair used: 0x37
[   10.320000] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   10.330000] ieee80211 phy0: Atheros AR9531 Rev:2 mem=0xb8100000, irq=47
[   10.340000] cfg80211: Calling CRDA for country: DE
[   10.340000] cfg80211: Regulatory domain changed to country: DE
[   10.350000] cfg80211:  DFS Master region: ETSI
[   10.350000] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   10.360000] cfg80211:   (2400000 KHz - 2483000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[   10.370000] cfg80211:   (5150000 KHz - 5250000 KHz @ 80000 KHz, 200000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[   10.380000] cfg80211:   (5250000 KHz - 5350000 KHz @ 80000 KHz, 200000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[   10.390000] cfg80211:   (5470000 KHz - 5590000 KHz @ 80000 KHz, 255000 KHz AUTO), (N/A, 2700 mBm), (0 s)
[   10.400000] cfg80211:   (5590000 KHz - 5650000 KHz @ 40000 KHz, 255000 KHz AUTO), (N/A, 2700 mBm), (600 s)
[   10.410000] cfg80211:   (5650000 KHz - 5725000 KHz @ 40000 KHz, 255000 KHz AUTO), (N/A, 2700 mBm), (0 s)
[   10.420000] cfg80211:   (57000000 KHz - 66000000 KHz @ 2160000 KHz), (N/A, 4000 mBm), (N/A)
[   20.330000] random: nonblocking pool is initialized
[   22.210000] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
[   22.230000] device eth1 entered promiscuous mode
[   22.230000] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   22.260000] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   22.810000] eth1: link up (1000Mbps/Full duplex)
[   22.810000] br-lan: port 1(eth1) entered forwarding state
[   22.820000] br-lan: port 1(eth1) entered forwarding state
[   22.820000] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[   22.860000] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   24.820000] br-lan: port 1(eth1) entered forwarding state
```

**Comment by burt2902** [comment]
Turned out that pl2303 usb-serial module is too old for the updated chip in my CZ_TAW1. New chip requires support for 23a3 product id which has been added in 5.x kernel series.

@lsochanowski: I'll be happy to make new CZ_TAW1 working and I have few questons:

1. Which openwrt version is GoHeishaMon baesd on?
2. Was kernel a stock one or compiled from sources?
3. If it was compiled from sources, how can I reproduce the dev env to be able to build patched pl2303 module?

**Comment by wolnypl** [comment]
Hello, 
First of all, @lsochanowski thanks for your  project.  I'm interested in it a lot. 

I have exactly the same error message o newly-bought cz-taw1  as burt2902
 
I'm also interested with answer to above questions or any other suggestions how this could be fixed. 
===
Sun Dec  4 14:44:56 2022 user.emerg syslog: panic: runtime error: invalid memory address or nil pointer dereference
Sun Dec  4 14:44:56 2022 user.emerg syslog: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x303c3c]
Sun Dec  4 14:44:56 2022 user.emerg syslog: 
Sun Dec  4 14:44:56 2022 user.emerg syslog: goroutine 1 [running]:
Sun Dec  4 14:44:56 2022 user.emerg syslog: go.bug.st/serial.(*unixPort).Write(0x0, 0x5d4a40, 0x6e, 0x6e, 0x1223ac00, 0x8b, 0xb2c97000)
Sun Dec  4 14:44:56 2022 user.emerg syslog: 	/go/src/go.bug.st/serial/serial_unix.go:88 +0x30
Sun Dec  4 14:44:56 2022 user.emerg syslog: main.send_command(0x5d4a40, 0x6e, 0x6e, 0x6e, 0x1)
Sun Dec  4 14:44:56 2022 user.emerg syslog: 	/go/src/github.com/lsochanowski/GoHeishaMon/taw2mqtt.go:1060 +0x94
Sun Dec  4 14:44:56 2022 user.emerg syslog: main.main()
Sun Dec  4 14:44:56 2022 user.emerg syslog: 	/go/src/github.com/lsochanowski/GoHeishaMon/taw2mqtt.go:572 +0xa80
Sun Dec  4 14:44:58 2022 user.emerg syslog: - init complete -

===

**Comment by sauliuslt** [comment]
Any progress on this issue? New cz-taw1 devices do not work with current version.

**Comment by lsochanowski** [comment]
Hello i've ocerlooked that now i'am processing the issue ;)

**Comment by sauliuslt** [comment]
> Hello i've ocerlooked that now i'am processing the issue ;)

Thanks! I hope this is easy fix.

**Comment by lsochanowski** [comment]
ok like you all say , we need to upgrade the core system , (openwrt) , i don't have new system , we need to extract it in the way we do it before (by locing upgrade mechanism and let orginal taw to download file but not to install ) when we get it we can replace wrt here in repo

**Comment by lsochanowski** [comment]
https://github.com/lsochanowski/GoHeishaMon/tree/NoWebSerwerButtonsAndLED/OS < here is whole openwrt we use today  problem is i don't have the pump or taw anymore we need someone with that hardware to process the case

**Comment by sauliuslt** [comment]
How can we help? I have new cz-taw1 with pump. Can you give instructions how to download taw from device?

**Comment by MiG-41** [comment]
@lsochanowski ,@sauliuslt , here is kernel :  https://www.mediafire.com/file/5ray9x0d70gjytu/openwrt-ar71xx-generic-cus531-16M-kernel.bin/file  , and filesystem: https://www.mediafire.com/file/gaqaqff8h9u3jak/openwrt-ar71xx-generic-cus531-16M-rootfs-squashfs.bin/file 
Orginal for CZ-TAW1  from September 2022 , a2wmain version 03.04.02
You can try to use only the kernel from it....

**Comment by MiG-41** [comment]
What is showing "cat /sys/kernel/debug/usb/devices" command:? , since at my it is:
`root@OpenWrt:/# cat /sys/kernel/debug/usb/devices

T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480  MxCh= 1
B:  Alloc=  4/800 us ( 1%), #Int=  2, #Iso=  0
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev= 3.14
S:  Manufacturer=Linux 3.14.0 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=ehci-platform
C:* #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=  0mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
E:  Ad=81(I) Atr=03(Int.) MxPS=   4 Ivl=256ms

T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480  MxCh= 4
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=058f ProdID=6254 Rev= 1.00
C:* #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=100mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
E:  Ad=81(I) Atr=03(Int.) MxPS=   1 Ivl=256ms

T:  Bus=01 Lev=02 Prnt=02 Port=01 Cnt=01 Dev#=  3 Spd=12   MxCh= 0
D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=067b ProdID=2303 Rev= 4.00
S:  Manufacturer=Prolific Technology Inc.
S:  Product=USB-Serial Controller D
C:* #Ifs= 1 Cfg#= 1 Atr=a0 MxPwr=100mA
I:* If#= 0 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=00 Driver=pl2303
E:  Ad=81(I) Atr=03(Int.) MxPS=  10 Ivl=1ms
E:  Ad=02(O) Atr=02(Bulk) MxPS=  64 Ivl=0ms
E:  Ad=83(I) Atr=02(Bulk) MxPS=  64 Ivl=0ms
`

**Comment by sauliuslt** [comment]
I cannot access device via ssh, only luci web admin is working for me.

**Comment by MiG-41** [comment]
Here is the newest orginal fw with a2wmain version 04.01.03 : https://www.mediafire.com/file/9z3ewl5g1aqqgk0/download_file.tgz/file

You can try to flash it , it will be orginal FW , if this will work with Service Cloud (connecting ,ect) , then it is included new drivers ,case will be only to upload GoHeishaMon there instead a2wmain....

**Comment by sauliuslt** [comment]
Uploaded this FW and it works perfectly.

**Comment by MiG-41** [comment]
You uploaded it with sysupgrade as well (so booth files ) and  Smart/Service Cloud works perfectly , or you upload only Kernel file with GoHeishamon sysupgrade file , and GoHeishamon works perfectly ?:)

**Comment by sauliuslt** [comment]
I uploaded both files from your archive file and smart could works fine.
I can try different combination, but you have to tell me what exact files to upload.

**Comment by MiG-41** [comment]
Probably this not helps.... 
@lsochanowski are you able to complile GoHeishamon taking as tamplate latest orginal files ?
I uplated some of them , but it is not compiling automaticly any more...

**Comment by lsochanowski** [comment]
on it @MiG-41

**Comment by lsochanowski** [comment]
fixed @MiG-41

**Comment by MiG-41** [comment]
@lsochanowski maybe you are ale to update all files from nawet orginal squash file? Since i update only pl2303.ko (hoping that this will be ok,but to be sure would be better to update all...

**Comment by MiG-41** [comment]
Anyway i tried newest 1.0.187 from @lsochanowski , and it run's ( so at least it will not stuck). It has changed/updated driver for pl2303 , so there is a chance ,that will ork , so @sauliuslt ,please try it.

**Comment by sauliuslt** [comment]
Uploaded latest files, but i don't see any messages. I suspect it did not read config file because after flashing FW white LED was solid and never turned off as in previous versions. I still cannot ssh " Connection refused" so i cannot check any logs.

**Comment by sauliuslt** [comment]
Any advice on this issue? I wonder why ssh connection is refused?

**Comment by burt2902** [comment]
@sauliuslt, you need to have ssh server enabled but it is disabled until you perform a first boot procedure. Luckily, there is a way to spawn the ssh server via MQTT as I have described [here](https://github.com/lsochanowski/GoHeishaMon/issues/23#issuecomment-1332254250). Make sure goheishamon is running and sending/responding to MQTT commands. Since it was crashing for me due to lack of /dev/ttyUSB0, I had to modify the config file and change the device to /dev/ttyS0 first. Hope this lets you move forward.

**Comment by MiG-41** [comment]
Try this one: https://www.mediafire.com/file/c2ac2ls56fhzxbz/GoHeishaMon1.1.191z166.zip/file
It should have new kernel , so hopfully support PL23a3 .

**Comment by burt2902** [comment]
Thank you for getting the kernel updated to support PL23a3.

PS: I will wait with closing the issue until there is an official release containing this change. I believe it would also make sense to update README.md to point at a release supporting newest CZ_TAW1 hardware.

**Comment by MiG-41** [comment]
@burt2902 so i understand ,that ou test it and it is working On your CZ-TAW1, have mqtt topics ,ect ?

**Comment by burt2902** [comment]
Yes, confirming that the issue is fixed with the kernel that properly handles 23a3 USB serial chip

**Comment by omenukas** [comment]
> Uploaded latest files, but i don't see any messages. I suspect it did not read config file because after flashing FW white LED was solid and never turned off as in previous versions. I still cannot ssh " Connection refused" so i cannot check any logs.

Same problem with me. Did you solve it?
