### ISSUE TITLE
CZ-TAW1 crashed after the original firmware update

### ISSUE THREAD

**Issue by omenukas** [lsochanowski/GoHeishaMon#29]
The CZ-TAW1 module was connected to the Aquarea Smart Cloud and stopped working sometime in the fall/winter. The "Status" indicator started flashing red. After rebooting the module it works for a while and then breaks again.
I decided to try sending the heat pump data to the Mqtt server.
I performed a firmware rewrite using the following link:
https://www.mediafire.com/file/c2ac2ls56fhzxbz/GoHeishaMon1.1.191z166.zip/file
Everything started working and I was already happy, but only half an hour. And then the data to mqtt stopped going. After rebooting the module, it's the same again - it works for a while and then stops again. The situation is the same as with the original firmware.
Do you have any ideas on how to solve this problem?

**Comment by omenukas** [comment]
Addition:
I have found that when I stop receiving mqtt messages from the heat pump, I can still send setting changes to the heat pump and they actually change on the unit.

**Comment by donpablos** [comment]
I'm using firmware from the link:
https://www.mediafire.com/file/c2ac2ls56fhzxbz/GoHeishaMon1.1.191z166.zip/file

I've the same problems like @omenukas

**Comment by donpablos** [comment]
I tried the procedure   to access ssh  ( to gather any  logs) :

  _panasonic_heat_pump/commands/OSCommand  umount /overlay
  panasonic_heat_pump/commands/OSCommand jffs2reset -y
  panasonic_heat_pump/commands/OSCommand  reboot_


and after rebooting your software  stops working, only helps me flash the device again .

**Comment by dimaregabriele** [comment]
hello, were you able to configure homeassistant ? you can help me ? @donpablos  @omenukas

**Comment by tomeeka** [comment]
@omenukas 
I have the same problem with the original firmware, it works for about a day.
After a reboot, it is working again for a while.
Have not tried GoHeishaMon yet.
Do you have any solution to solve this problem? Can this be a HW problem?
My adapter is brand new, doing this since day 1.

**Comment by omenukas** [comment]
I solved the problem by buying this module:
https://www.tindie.com/products/thehognl/heishamon-communication-pcb/
It works perfectly, without any problems, and I will throw the CZ-TAW1 in the trash 😀 Trying to solve the problem, neither changing the module, nor changing the pump motherboard (the changes were made by Panasonic representatives themselves), nor changing the Internet did not help.

**Comment by omenukas** [comment]
@dimaregabriele 
Try this perfect tool:
https://github.com/edterbak/NodeRed_Heishamon_control

**Comment by adnovea** [comment]
I first tried with the version downloaded in Aug 2023 (_**v1.0.166** I guess  Jan 12  2021 /usr/bin/GoHeishaMon_MIPSUP_) without success so I SSH the module and ran manually GoHeishaMon_MIPSUP :

```
root@CZ-TAW1B:~# /usr/bin/GoHeishaMon_MIPSUPX
try to update configfile: /etc/gh/configFound port: /dev/ttyS0
Found port: /dev/ttyUSB0
Invalid serial port
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x303c3c]

goroutine 1 [running]:
go.bug.st/serial.(*unixPort).Write(0x0, 0x5d4a40, 0x6e, 0x6e, 0x123c74c8, 0xc33d7c, 0xb2c97000)
        /go/src/go.bug.st/serial/serial_unix.go:88 +0x30
main.send_command(0x5d4a40, 0x6e, 0x6e, 0x6e, 0x1)
        /go/src/github.com/lsochanowski/GoHeishaMon/taw2mqtt.go:1060 +0x94
main.main()
        /go/src/github.com/lsochanowski/GoHeishaMon/taw2mqtt.go:572 +0xa80
```
I found this post https://github.com/lsochanowski/GoHeishaMon/issues/27#issuecomment-1374619385 and tried again but

**GoHeishaMon (version 1.1.191 ) crashes randomly**

I wrote a short script to run GHM and check when it crashes.
Actually after few minutes to several hours.
```
Start GoHeishaMon
-----------------
Sun Nov  5 08:21:51 CET 2023 Start GoHeishaMon Process
Sun Nov  5 08:44:11 CET 2023 Crash ...
Sun Nov  5 08:44:12 CET 2023 Start GoHeishaMon Process
Sun Nov  5 08:54:06 CET 2023 Crash ...
Sun Nov  5 08:54:07 CET 2023 Start GoHeishaMon Process
Sun Nov  5 09:27:14 CET 2023 Crash ...
Sun Nov  5 09:27:15 CET 2023 Start GoHeishaMon Process
Sun Nov  5 09:41:03 CET 2023 Crash ...
Sun Nov  5 09:41:04 CET 2023 Start GoHeishaMon Process
Sun Nov  5 09:49:42 CET 2023 Crash ...
Sun Nov  5 09:49:43 CET 2023 Start GoHeishaMon Process
Sun Nov  5 10:54:29 CET 2023 Crash ...
Sun Nov  5 10:54:30 CET 2023 Start GoHeishaMon Process
Sun Nov  5 11:12:05 CET 2023 Crash ...
Sun Nov  5 11:12:06 CET 2023 Start GoHeishaMon Process
Sun Nov  5 13:05:24 CET 2023 Crash ...
Sun Nov  5 13:05:25 CET 2023 Start GoHeishaMon Process
```
Latest version **GoHeishaMon (version 1.0.192 ) also crashes randomly**

I have no idea where to look to avoid these crashes.
